package vm

type OpCode = int

const (
	OP_LOAD_GLOBAL  = "LOAD_GLOBAL"
	OP_LOAD_CONST   = "LOAD_CONST"
	OP_POP_CONST    = "POP_CONST"
	OP_LOAD_VAR     = "LOAD_VAR"
	OP_LOAD_TYPE    = "LOAD_TYPE"
	FUNC_CALL       = "FUNC_CALL"
	OP_PUSH_CONST   = "PUSH_CONST"
	OP_PUSH_SCOPE   = "PUSH_SCOPE"
	OP_POP_SCOPE    = "POP_SCOPE"
	OP_NOT          = "NOT"
	OP_OR           = "OR"
	OP_AND          = "AND"
	OP_NEGATIVE     = "OP_NEGATIVE"
	OP_STORE_GLOBAL = "STORE_GLOBAL"
	OP_DECL_VAR     = "DECL_VAR"
	OP_SET_VAR      = "SET_VAR"
	OP_MULT         = "MULT"
	OP_EQ           = "EQ"
	OP_EQ_2         = "EQ_2"
	OP_CMP          = "CMP"
	OP_ADD          = "ADD"
	OP_DIV          = "DIV"
	OP_SUB          = "SUB"
	OP_DECL_TYPE    = "DECL_TYPE"
	OP_RETURN       = "RETURN"
	OP_HALT         = "HALT"
	OP_DEBUG_PRINT  = "DEBUG_PRINT"
	OP_LABEL        = "LABEL"
	OP_JUMP_NOT     = "JUMP_NOT"
	OP_JUMP_IF      = "JUMP_IF"
	OP_JUMP         = "JUMP"
	OP_ARR_INIT     = "ARR_INIT"
	OP_ARR_APPEND   = "ARR_APPEND"
	OP_ARR_PUSH     = "ARR_PUSH"
)
