package vm

type OpCode = int

const (
	OP_LOAD_GLOBAL           = "LOAD_GLOBAL"
	OP_LOAD_CONST            = "LOAD_CONST"
	OP_POP_CONST             = "POP_CONST"
	OP_LOAD_VAR              = "LOAD_VAR"
	OP_LOAD_TYPE             = "LOAD_TYPE"
	OP_LOAD_TYPE_INFER       = "LOAD_TYPE_INFER"
	CALL                     = "CALL"
	OP_PUSH_CONST            = "PUSH_CONST"
	OP_PUSH_SCOPE            = "PUSH_SCOPE"
	OP_POP_SCOPE             = "POP_SCOPE"
	OP_NOT                   = "NOT"
	OP_OR                    = "OR"
	OP_AND                   = "AND"
	OP_NEGATIVE              = "OP_NEGATIVE"
	OP_STORE_GLOBAL          = "STORE_GLOBAL"
	OP_DECL_VAR              = "DECL_VAR"
	OP_SET_VAR               = "SET_VAR"
	OP_MULT                  = "MULT"
	OP_EQ                    = "EQ"
	OP_EQ_2                  = "EQ_2"
	OP_CMP                   = "CMP"
	OP_ADD                   = "ADD"
	OP_DIV                   = "DIV"
	OP_ARR_LOAD              = "ARR_LOAD"
	OP_SUB                   = "SUB"
	OP_DECL_TYPE             = "DECL_TYPE"
	OP_RETURN                = "RETURN"
	OP_HALT                  = "HALT"
	OP_DEBUG_PRINT           = "DEBUG_PRINT"
	OP_LABEL                 = "LABEL"
	OP_JUMP_NOT              = "JUMP_NOT"
	OP_JUMP_IF               = "JUMP_IF"
	OP_JUMP                  = "JUMP"
	OP_ARR_INIT              = "ARR_INIT"
	OP_ARR_TYPE              = "ARR_TYPE"
	OP_ARR_APPEND            = "ARR_APPEND"
	OP_ARR_PUSH              = "ARR_PUSH"
	OP_LEN                   = "LEN"
	OP_OBJ_TYPE              = "OBJ_TYPE"
	OP_OBJ_TYPE_LOAD_DEFAULT = "OBJ_TYPE_LOAD_DEFAULT"
	OP_OBJ_TYPE_SET_FIELD    = "OBJ_TYPE_SET_FIELD"
	OP_OBJ_INIT              = "OBJ_INIT"
	OP_OBJ_SET_FIELD         = "OBJ_SET_FIELD"
	OP_OBJ_LOAD              = "OBJ_LOAD"

	OP_FUNC_BEGIN                  = "FUNC_BEGIN"
	OP_FUNC_END                    = "FUNC_END"
	OP_FUNC_INIT                   = "FUNC_INIT"
	OP_FUNC_SET_PARAM              = "FUNC_SET_PARAM"
	OP_FUNC_SET_PARAM_WITH_DEFAULT = "FUNC_SET_PARAM_WITH_DEFAULT"
	OP_FUNC_SET_RET                = "FUNC_SET_RET"
	OP_CALL                        = "CALL"

	OP_PUSH_ARG       = "PUSH_ARG"
	OP_PUSH_NAMED_ARG = "PUSH_NAMED_ARG"

	OP_FUNC_TYPE           = "FUNC_TYPE"
	OP_FUNC_TYPE_SET_RET   = "FUNC_TYPE_SET_RET"
	OP_FUNC_TYPE_SET_PARAM = "FUNC_TYPE_SET_PARAM"
)
